### ISSUE TITLE
After update: Failed to activate the jshint package

### ISSUE THREAD

**Issue by KINFOO** [sindresorhus/atom-jshint#100]
Hi,

I am using __Atom 1.0.2__ and __JsHint 1.3.9__.

When I open atom, I _immediately_ have an error message in a red pop up.

Here is related stack trace:

[Enter steps to reproduce below:]

1. Open __Atom__

**Atom Version**: 1.0.2-9432598
**System**: Ubuntu 15.04
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.9

### Stack Trace

Failed to activate the jshint package

```
At Arguments to path.join must be strings

TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:449:13)
    at findFile (/home/kevin/.atom/packages/jshint/load-config.js:57:66)
    at loadNpmConfig (/home/kevin/.atom/packages/jshint/load-config.js:114:12)
    at loadConfig (/home/kevin/.atom/packages/jshint/load-config.js:138:16)
    at lint (/home/kevin/.atom/packages/jshint/index.js:218:34)
    at registerEvents (/home/kevin/.atom/packages/jshint/index.js:271:2)
    at Object.plugin.activate (/home/kevin/.atom/packages/jshint/index.js:318:2)
    at Package.module.exports.Package.activateNow (/home/kevin/.local/share/atom/resources/app.asar/src/package.js:240:19)
    at /home/kevin/.local/share/atom/resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/home/kevin/.local/share/atom/resources/app.asar/src/package.js:165:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jsformat"
    ]
  },
  "jshint": {}
}
```

### Installed Packages

```coffee
# User
jshint, v1.3.9
linter-pep8, v1.0.0
minimap, v4.11.2
pigments, v0.8.4
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by KINFOO** [comment]
Thanks

**Comment by kane-thornwyrd** [comment]
Help :sob: 

1. Open Atom.

**Atom Version**: 1.0.2
**System**: "Fedora release
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.10


### Stack Trace

Failed to activate the jshint package

```
At ENOENT: no such file or directory, uv_chdir

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs/polyfills.js:14:9)
    at lint (/home/jctherond/.atom/packages/jshint/index.js:208:10)
    at registerEvents (/home/jctherond/.atom/packages/jshint/index.js:271:2)
    at Object.plugin.activate (/home/jctherond/.atom/packages/jshint/index.js:318:2)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
    at /usr/share/atom/resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:412:46)
    at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:645:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "pairing-chat",
      "backbonejs-snippets",
      "pairing-chat",
      "backbonejs-snippets",
      "pairing-chat",
      "node-resolver"
    ],
    "projectHome": "~/project"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-alignment, v0.12.1
atom-backbone, v0.6.1
autocomplete-modules, v1.0.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
docblockr, v0.7.3
file-type-icons, v0.7.0
fold-functions, v0.2.1
gulp-manager, v0.2.0
gulp-snippets, v0.6.1
jshint, v1.3.10
linter, v1.2.4
minimap, v4.12.1
motepair, v0.20.0
project-manager, v1.15.11
project-view, v0.1.2
remote-edit, v1.8.14
save-session, v0.15.7
seti-syntax, v0.4.0
seti-ui, v0.7.1
svn, v0.0.7
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by damonkreft** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.10


### Stack Trace

Failed to activate the jshint package

```
At ENOENT: no such file or directory, uv_chdir

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at lint (/home/damon/.atom/packages/jshint/index.js:208:10)
    at registerEvents (/home/damon/.atom/packages/jshint/index.js:271:2)
    at Object.plugin.activate (/home/damon/.atom/packages/jshint/index.js:318:2)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
    at /usr/share/atom/resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:436:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "autoclose-html"
    ],
    "ignoredNames": [
      "dist"
    ]
  },
  "jshint": {
    "supportLintingJsx": true
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.5.8
highlight-selected, v0.10.1
jshint, v1.3.10
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by VictorCoding** [comment]
Similar to the above scenarios happens to me.
