### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by ianwalter** [sindresorhus/atom-jshint#101]
Steps to reproduce:

1. Open a JavaScript file in Atom (the file in question does have a jshint violation).

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.9

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /Users/ian/.atom/packages/jshint/node_modules/jshint/src/cli.js:200

TypeError: Cannot read property 'split' of null
  at loadIgnores (/Users/ian/.atom/packages/jshint/node_modules/jshint/src/cli.js:200:43)
  at Object.exports.gather (/Users/ian/.atom/packages/jshint/node_modules/jshint/src/cli.js:566:35)
  at lint (/Users/ian/.atom/packages/jshint/index.js:211:20)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
  2x -0:18.3.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:01.9.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.pyc",
      ".DS_Store"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atom-handlebars, v1.0.0
autocomplete-python, v0.5.1
color-picker, v2.0.10
ember-cli-helper, v0.7.2
file-icons, v1.5.8
git-plus, v5.2.2
jshint, v1.3.9
local-history, v3.2.3
sync-settings, v0.5.0
wakatime, v4.0.12

# Dev
No dev packages
```

**Comment by sindresorhus** [comment]
That error is coming from JSHint, not this plugin. Make sure your code is valid.

**Comment by maennchen** [comment]
Broken code should not be able to crash the editor.

If I execute `jshint .` in the project root, i get 0 errors. Atom still crashes.
