### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by momotan210** [sindresorhus/atom-jshint#107]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.10

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/momota/.atom/packages/jshint/index.js:134

TypeError: Cannot read property '0' of undefined
  at updateStatusbar (/Users/momota/.atom/packages/jshint/index.js:134:15)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
  2x -0:55.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:53.9.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:52.3.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:51.2.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:46.5.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:37.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:36.4.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:35.1.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:33.4.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:27.4.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:14.7.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.4.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:05.1.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:02.6.0 blur (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.8.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "gist-it",
      "wrap-guide",
      "term2"
    ],
    "themes": [
      "seti-ui",
      "monokai-soda"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
Sublime-Style-Column-Selection, v1.3.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
file-icons, v1.5.8
highlight-selected, v0.10.1
jshint, v1.3.10
language-babel, v0.10.4
language-scala, v1.1.3
linter, v1.2.4
minimap, v4.12.1
minimap-autohide, v0.10.0
minimap-git-diff, v4.1.7
monokai-soda, v0.5.0
react, v0.12.6
seti-ui, v0.7.1
travis-ci-status, v0.16.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by Pavel-Evdokimov** [comment]
same issue
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.2
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.10


### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /home/pevdokimov/.atom/packages/jshint/index.js:134

TypeError: Cannot read property '0' of undefined
    at updateStatusbar (/home/pevdokimov/.atom/packages/jshint/index.js:134:15)
    at complete (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
    at delayed (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)
```

### Commands

```
     -0:36.7.0 tree-view:move (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:35.4.0 editor:select-to-end-of-word (atom-text-editor.editor.mini.is-focused)
     -0:34.7.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -0:34.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:27.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:22.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:21.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:13.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:11.9.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.8
jshint, v1.3.10
language-javascript-jsx, v0.3.7
linter, v1.2.4
node-debugger, v1.1.7

# Dev
No dev packages
```

**Comment by iamcc** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.10


### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/cc/.atom/packages/jshint/index.js:134

TypeError: Cannot read property '0' of undefined
  at updateStatusbar (/Users/cc/.atom/packages/jshint/index.js:134:15)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
  2x -0:42.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 core:close (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "jshint": {
    "supportLintingJsx": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.9
auto-update-packages, v1.0.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.5.8
git-log, v0.4.1
go-plus, v3.4.3
highlight-line, v0.11.0
highlight-selected, v0.10.1
jshint, v1.3.10
minimap, v4.12.1
pretty-json, v0.4.1
project-manager, v1.15.11
react, v0.12.6
recent-projects, v0.7.6
refactor, v0.5.1
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by Silom** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.3
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.10


### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/Silom/.atom/packages/jshint/index.js:134

TypeError: Cannot read property '0' of undefined
  at updateStatusbar (/Users/Silom/.atom/packages/jshint/index.js:134:15)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
     -0:21.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:21.2.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:20.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:20.3.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:20 core:backspace (atom-text-editor.editor.is-focused)
  7x -0:19.5.0 core:move-down (atom-text-editor.editor.is-focused)
 16x -0:18.4.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:13.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12 core:select-up (atom-text-editor.editor.is-focused)
     -0:10.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".min.js",
      ".map",
      ".vagrant"
    ],
    "disabledPackages": [
      "neon-selection",
      "language-objective-c",
      "language-ruby-on-rails",
      "language-toml",
      "keybinding-resolver",
      "emmet",
      "node-resolver"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "projectHome": "/Users/Silom/Projects",
    "audioBeep": false
  },
  "jshint": {
    "supportLintingJsx": true,
    "validateOnlyOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
auto-update-packages, v1.0.0
autocomplete-paths, v1.0.2
color-picker, v2.0.11
file-icons, v1.6.2
jsformat, v0.9.0
jshint, v1.3.10
language-babel, v0.10.4
language-ejs, v0.2.0
language-jade, v0.6.2
log-console, v0.2.0
minimap, v4.12.1
pigments, v0.9.2
react, v0.12.6
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by lebowski89** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.4.0


### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\mike.geldard\.atom\packages\jshint\index.js:138

TypeError: Cannot read property '0' of undefined
  at updateStatusbar (C:\Users\mike.geldard\.atom\packages\jshint\index.js:138:15)
  at displayErrors (C:\Users\mike.geldard\.atom\packages\jshint\index.js:181:2)
  at complete (C:\Users\mike.geldard\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
  at delayed (C:\Users\mike.geldard\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)

```

### Commands

```
     -3:37.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:37 core:paste (atom-text-editor.editor.is-focused)
     -3:31.9.0 core:undo (atom-text-editor.editor.is-focused)
     -2:13.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:13.3.0 core:paste (atom-text-editor.editor.is-focused)
     -2:10.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:45.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:44.6.0 core:paste (atom-text-editor.editor.is-focused)
  4x -1:43.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Zen",
      "atom-jshint",
      "autocomplete-paths",
      "git-difftool",
      "minimap-git-diff",
      "webbox-color",
      "close-tags",
      "autoclose-html"
    ],
    "autoHideMenuBar": true
  },
  "jshint": {
    "supportLintingJsx": true,
    "onlyConfig": true,
    "validateOnlyOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
clipboard-plus, v0.5.1
file-icons, v1.6.7
highlight-line, v0.11.0
highlight-selected, v0.10.1
jshint, v1.4.0
line-ending-converter, v1.3.2
minimap, v4.13.1
pigments, v0.11.0
react, v0.12.6
sync-settings, v0.6.0
tool-bar, v0.1.8
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by lebowski89** [comment]
After further investigation, this error only happens for me when there are no errors found by JSHint. Can anyone else confirm this is the case for them?

**Comment by lebowski89** [comment]
Here's our problem: https://github.com/sindresorhus/atom-jshint/blob/master/index.js#L124

I'd suggest `error = error.length ? error[0] : {};`
