### ISSUE TITLE
Uncaught Error: Cannot find module 'exit'

### ISSUE THREAD

**Issue by vingorius** [sindresorhus/atom-jshint#118]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.13
**System**: Unknown Windows Version
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.7.0
### Stack Trace

Uncaught Error: Cannot find module 'exit'

```
At module.js:336

Error: Cannot find module 'exit'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\jshint\node_modules\jshint\node_modules\cli\cli.js:68:12)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\jshint\node_modules\jshint\node_modules\cli\index.js:1:80)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\jshint\node_modules\jshint\src\cli.js:5:25)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at lazy (C:\Users\김종호\.atom\packages\jshint\node_modules\lazy-req\index.js:34:36)
  at C:\Users\김종호\.atom\packages\jshint\node_modules\lazy-req\index.js:8:11
  at lint (C:\Users\김종호\.atom\packages\jshint\index.js:254:14)
  at complete (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
  at delayed (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)

```
### Commands

```
     -2:59.1.0 settings-view:open (atom-pane.pane.active)
  4x -2:48.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:35.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:34.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
jshint, v1.7.0

# Dev
No dev packages
```

**Comment by kenborge** [comment]
I think this is because of unicode characters in the hole folder path. It get this issue to, and similar issues an a lot of atom packages. It seems like Atom just doesn't handle unicode character in paths

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
