### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, uv_chdir

### ISSUE THREAD

**Issue by barrycarr** [sindresorhus/atom-jshint#123]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.0
### Stack Trace

Uncaught Error: EPERM: operation not permitted, uv_chdir

```
At /C:/Users/barry.carr/.atom/packages/jshint/index.js:245

Error: EPERM: operation not permitted, uv_chdir
  at Error (native)
  at lint (C:\Users\barry.carr\.atom\packages\jshint\index.js:245:10)
  at complete (C:\Users\barry.carr\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
  at delayed (C:\Users\barry.carr\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)

```
### Commands

```
     -2:20.8.0 core:delete (atom-text-editor.editor.is-focused)
     -2:20.4.0 core:cut (atom-text-editor.editor.is-focused)
 26x -2:19.7.0 core:move-up (atom-text-editor.editor.is-focused)
 12x -2:17.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:16.6.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -2:16.1.0 core:move-down (atom-text-editor.editor.is-focused)
 33x -2:15.2.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -2:13.3.0 core:move-down (atom-text-editor.editor.is-focused)
 13x -2:12.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -2:10.5.0 core:delete (atom-text-editor.editor.is-focused)
     -2:09.4.0 core:save (atom-text-editor.editor.is-focused)
  6x -2:08.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:06.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:06.3.0 core:delete (atom-text-editor.editor.is-focused)
     -1:05.9.0 core:cut (atom-text-editor.editor.is-focused)
     -1:04.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-beautify, v0.28.14
atom-typescript, v7.0.1
atom-yeoman, v0.3.14
autocomplete-modules, v1.2.0
editorconfig, v1.2.0
FSharp, vundefined
jshint, v1.8.0
language-docker, v1.1.3
language-fsharp, v0.8.4
language-gherkin, v1.0.2
language-gitignore, v0.2.0
language-groovy, v0.4.0
language-powershell, v2.1.0
language-scala, v1.1.3
linter, v1.6.0
linter-tslint, v0.4.0
minimap, v4.13.4
node-debugger, v1.1.8
omnisharp-atom, vundefined
seti-syntax, v0.4.0
seti-ui, v0.8.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment]
Can you give steps to replicate this error?

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
