### ISSUE TITLE
Uncaught TypeError: element.addEventListener is not a function

### ISSUE THREAD

**Issue by alcaitiff** [sindresorhus/atom-jshint#124]
[Enter steps to reproduce below:]

1. Open any file
2. This happens

**Atom Version**: 1.2.0-dev-17d962f
**System**: Ubuntu 12.04.5
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.0

### Stack Trace

Uncaught TypeError: element.addEventListener is not a function

```
At /usr/local/share/atom/resources/app.asar/src/delegated-listener.js:36

TypeError: element.addEventListener is not a function
  at listen (/usr/local/share/atom/resources/app.asar/src/delegated-listener.js:36:11)
  at [object Object].Tooltip.init (/usr/local/share/atom/resources/app.asar/src/tooltip.js:83:28)
  at new Tooltip (/usr/local/share/atom/resources/app.asar/src/tooltip.js:18:8)
  at TooltipManager.module.exports.TooltipManager.add (/usr/local/share/atom/resources/app.asar/src/tooltip-manager.js:50:17)
  at addReasons (/home/98255584072/.atom/packages/jshint/index.js:186:30)
  at displayError (/home/98255584072/.atom/packages/jshint/index.js:206:2)
  at /home/98255584072/.atom/packages/jshint/index.js:214:10
  at arrayEach (/usr/local/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at displayErrors (/home/98255584072/.atom/packages/jshint/index.js:213:4)
  at lint (/home/98255584072/.atom/packages/jshint/index.js:293:2)
  at complete (/usr/local/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/usr/local/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
     -3:33.5.0 project-ring:toggle (atom-pane.pane.active)
     -1:46.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-php",
      "pigments"
    ],
    "fileEncoding": "iso88591"
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.10.11
atom-jshint, v2.0.0
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.1.0
jsformat, v0.9.0
jshint, v1.8.0
minimap, v4.13.3
minimap-pigments, v0.1.6
php-cs-fixer, v2.4.0
project-manager, v2.5.2
project-ring, v0.35.2
project-view, v0.1.2
recent-projects, v0.8.8

# Dev
No dev packages
```

**Comment by KINFOO** [comment]
:+1:

**Comment by evjan** [comment]
I get the same error, Atom Beta 1.1.0-beta1

**Comment by kukac7** [comment]
:+1:

**Comment by rohan-deshpande** [comment]
Yup this just started happening to me suddenly! Been using this fine for weeks.

**Comment by okwangxing** [comment]
I get the same error, Atom 1.1.0, Mac 10.11

**Comment by rohanray** [comment]
why is this closed? Is it fixed?

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.1


### Stack Trace

Uncaught TypeError: element.addEventListener is not a function

```
At C:\Users\rohan\AppData\Local\atom\app-1.1.0\resources\app.asar\src\delegated-listener.js:36

TypeError: element.addEventListener is not a function
    at listen (C:\Users\rohan\AppData\Local\atom\app-1.1.0\resources\app.asar\src\delegated-listener.js:36:11)
    at [object Object].Tooltip.init (C:\Users\rohan\AppData\Local\atom\app-1.1.0\resources\app.asar\src\tooltip.js:83:28)
    at new Tooltip (C:\Users\rohan\AppData\Local\atom\app-1.1.0\resources\app.asar\src\tooltip.js:18:8)
    at TooltipManager.module.exports.TooltipManager.add (C:\Users\rohan\AppData\Local\atom\app-1.1.0\resources\app.asar\src\tooltip-manager.js:50:17)
    at addReasons (C:/Users/rohan/.atom/packages/jshint/index.js:169:32)
    at displayError (C:/Users/rohan/.atom/packages/jshint/index.js:189:2)
    at C:/Users/rohan/.atom/packages/jshint/index.js:196:24
    at arrayEach (C:\Users\rohan\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (C:\Users\rohan\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3345:13)
    at displayErrors (C:/Users/rohan/.atom/packages/jshint/index.js:196:4)
```

### Commands

```
     -0:05.7.0 tree-view:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.2.0
atom-jshint, v2.0.0
color-tabs, v0.1.8
css-color-underline, v1.0.1
file-types, v0.5.1
jshint, v1.8.1
language-spacebars, v0.2.2
linter, v1.9.1
linter-handlebars, v2.2.0
meteor-api, v2.20.0
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by sylistine** [comment]
Yeah this is certainly not fixed, I'm getting this issue right now.
Atom v1.1.0
jshint v1.8.1

**Comment by erikbarke** [comment]
Same issue here...
Atom 1.1.0
Jshint 1.8.1

**Comment by FlorianBezagu** [comment]
:+1: 

Same here ... and same versions ...
Atom 1.1.0
jshint 1.8.1
Ubuntu 14.04

**Comment by sclausen** [comment]
:+1:

**Comment by timqian** [comment]
same here same versions again

**Comment by JonasDoebertin** [comment]
Same here.

**Comment by vassyz** [comment]
**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.1

**Comment by jasondonnette** [comment]
I am getting this issue too. I disabled all 3rd party packages, and still get the error. 

Atom 1.1.0, Mac OSX 10.11.1, jshint 1.8.1
