### ISSUE TITLE
Uncaught Error: Cannot find module 'jshint'

### ISSUE THREAD

**Issue by ANRION** [sindresorhus/atom-jshint#130]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.0
### Stack Trace

Uncaught Error: Cannot find module 'jshint'

```
At module.js:336

Error: Cannot find module 'jshint'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Администратор\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at lazy (C:\Users\Администратор\.atom\packages\jshint\node_modules\lazy-req\index.js:34:36)
  at C:\Users\Администратор\.atom\packages\jshint\node_modules\lazy-req\index.js:8:11
  at lint (C:\Users\Администратор\.atom\packages\jshint\index.js:256:131)
  at complete (C:\Users\Администратор\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
  at delayed (C:\Users\Администратор\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)

```
### Commands

```
     -2:10.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:07.3.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.mini.is-focused)
     -2:03.5.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -2:00.2.0 symbols-view:toggle-project-symbols (atom-text-editor.editor.is-focused)
     -1:50.6.0 open-on-github:blame (atom-text-editor.editor.is-focused)
     -1:46 open-on-github:copy-url (atom-text-editor.editor.is-focused)
     -1:41.6.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -1:39 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
     -1:35.9.0 editor:select-line (atom-text-editor.editor.is-focused)
     -1:33.6.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:11.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:13.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10.6.0 grammar-selector:show (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
jshint, v1.8.0

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment]
Perhaps you could try reinstalling? Worked for some in a [similar issue](https://github.com/sindresorhus/atom-jshint/issues/92).

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
