### ISSUE TITLE
Uncaught Error: EIO: i/o error, uv_chdir

### ISSUE THREAD

**Issue by correiad21** [sindresorhus/atom-jshint#137]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.1
### Stack Trace

Uncaught Error: EIO: i/o error, uv_chdir

```
At /Users/Correia/.atom/packages/jshint/index.js:226

Error: EIO: i/o error, uv_chdir
    at Error (native)
    at lint (/Users/Correia/.atom/packages/jshint/index.js:226:10)
    at complete (/Users/Correia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
    at delayed (/Users/Correia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)
```
### Commands

```
  4x -9:40 core:backspace (atom-text-editor.editor.is-focused)
  2x -9:36.7.0 core:save (atom-text-editor.editor.is-focused)
  7x -7:52.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:23.3.0 core:save (atom-text-editor.editor.is-focused)
  4x -6:21.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:55.4.0 core:cut (atom-text-editor.editor.is-focused)
     -5:52.4.0 core:paste (atom-text-editor.editor.is-focused)
  4x -5:51.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:37 core:save (atom-text-editor.editor.is-focused)
  9x -5:18.7.0 core:undo (atom-text-editor.editor.is-focused)
     -4:53.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:00.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:17.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "SFTP-deployment"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
