### ISSUE TITLE
Cannot find module grim

### ISSUE THREAD

**Issue by rohan-deshpande** [sindresorhus/atom-jshint#138]
**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.1
### Stack Trace

Failed to load the jshint package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\rohandeshpande\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\rohandeshpande\.atom\packages\jshint\node_modules\event-kit\lib\disposable.js:4:10)
    at Object.<anonymous> (C:\Users\rohandeshpande\.atom\packages\jshint\node_modules\event-kit\lib\disposable.js:43:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\rohandeshpande\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```
### Config

``` json
{
  "core": {},
  "jshint": {
    "supportLintingJsx": true
  }
}
```
### Installed Packages

``` coffee
# User
jshint, v1.8.1
language-babel, v0.15.12
seti-icons, v0.4.5

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment]
Perhaps you could try reinstalling? Worked for some in a [similar issue](https://github.com/sindresorhus/atom-jshint/issues/92).

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
