### ISSUE TITLE
Uncaught TypeError: Cannot read property 'jquery' of null

### ISSUE THREAD

**Issue by facultymatt** [sindresorhus/atom-jshint#142]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.4
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.2

### Stack Trace

Uncaught TypeError: Cannot read property 'jquery' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tooltip-manager.js:26

TypeError: Cannot read property 'jquery' of null
    at TooltipManager.module.exports.TooltipManager.add (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip-manager.js:26:17)
    at addReasons (/Users/spmatt/.atom/packages/jshint/index.js:169:32)
    at displayError (/Users/spmatt/.atom/packages/jshint/index.js:189:2)
    at /Users/spmatt/.atom/packages/jshint/index.js:196:24
    at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
    at displayErrors (/Users/spmatt/.atom/packages/jshint/index.js:196:4)
    at lint (/Users/spmatt/.atom/packages/jshint/index.js:270:2)
    at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
    at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-jade, v0.3.0
hidpi, v0.7.0
jshint, v1.8.2

# Dev
No dev packages
```

**Comment by stocks29** [comment]
+1

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/atom-jshint/issues/141

I don't have time to look into this.

**Comment by hipstern** [comment]
was there any update today? i'm getting this error all of the sudden in the last hour. everything was fine before.

**Comment by hipstern** [comment]
this could be Atom 1.1.0 related. i'm getting a lot of errors from other packages as well ever since the update took place an hour ago.

**Comment by thadk** [comment]
Perhaps jQuery deprecation from `require atom` was fully completed in Atom 1.1? Believe there may have been a second issue this morning before this one, now resolved. https://atom.io/docs/latest/upgrading-to-1-0-apis-upgrading-your-package
