### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by akaRem** [sindresorhus/atom-jshint#151]
[Enter steps to reproduce below:]
1. Open atom
2. Click on any tab with source (.md .sh)

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3
### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
  at Object.global.__grim__.deprecate (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
  at TextEditor.module.exports.TextEditor.onDidChangeScrollTop (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/text-editor.js:375:12)
  at registerEvents (/Users/me/.atom/packages/jshint/index.js:324:32)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
  at Pane.module.exports.Pane.activateItem (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/src/pane.js:312:21)
  at atom-tabs.TabBarView.onMouseDown (/opt/homebrew-cask/Caskroom/atom/1.0.16/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)

```
### Commands

```
     -0:12.4.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "about",
      "language-clojure",
      "language-c",
      "language-coffee-script",
      "language-csharp",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby-on-rails",
      "language-toml",
      "package-generator",
      "update-package-dependencies",
      "welcome",
      "nuclide-type-hint",
      "nuclide-debugger-atom",
      "nuclide-splits",
      "ide-flow",
      "linter-eslint",
      "linter-xo",
      "linter-js-standard",
      "linter-gjslint",
      "linter-jscs",
      "linter-jshint",
      "linter-marlint",
      "spell-check"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.8.4
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-python, v0.10.3
autohide-tree-view, v0.25.1
color-picker, v2.0.13
copy-filename, v1.0.1
file-type-icons, v0.7.3
git-diff-details, v0.21.0
git-log, v0.4.1
jshint, v1.8.3
language-dots, v0.0.4
language-js-specs, v0.1.0
linter, v1.10.0
linter-flake8, v1.9.1
linter-flow, v4.0.0
linter-js-yaml, v1.2.0
linter-jsonlint, v1.0.1
linter-liferay, v2.1.0
linter-package-json-validator, v0.2.2
linter-pep257, v0.3.1
linter-pep8, v1.0.1
linter-pylint, v1.0.3
linter-shellcheck, v1.0.2
minimap, v4.16.0
minimap-git-diff, v4.1.8
nuclide-flow, v0.0.32
pigments, v0.18.1
react, v0.12.10
source-preview-react, v0.2.0
symbols-tree-view, v0.10.1
tree-ignore, v0.2.6
tree-view-git-branch, v0.0.6
tree-view-open-files, v0.3.0
tualo-git-context, v0.6.16

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment]
Does the issue persist if you disable atom-jshint, restart atom, and enable atom-jshint?

**Comment by jacarma** [comment]
Yes It persists in my installation after disable, restart and enable.

**Comment by jacarma** [comment]
The variable stack defined a few lines before the error contains a string instead of an array. The content is:
```
rror at Object.global.__grim__.deprecate (/usr/share/atom/resources/app.asar/node_modules/grim/lib/grim.js:51:15) at TextEditor.module.exports.TextEditor.onDidChangeScrollTop (/usr/share/atom/resources/app.asar/src/text-editor.js:375:12) at registerEvents (/home/javier/.atom/packages/jshint/index.js:324:32) at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11) at /usr/share/atom/resources/app.asar/src/pane-container.js:333:27 at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11) at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:248:22) 
```

**Comment by jacarma** [comment]
It could be a problem with nuclide, I uninstalled it and the error was gone.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
