### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by calvintps** [sindresorhus/atom-jshint#152]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Microsoft Windows 8.1 Single Language
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3
### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /C:/Users/CalvinLappy/.atom/packages/jshint/index.js:185

TypeError: Cannot read property 'querySelector' of null
    at addReasons (C:/Users/CalvinLappy/.atom/packages/jshint/index.js:168:41)
    at displayError (C:/Users/CalvinLappy/.atom/packages/jshint/index.js:194:2)
    at C:/Users/CalvinLappy/.atom/packages/jshint/index.js:201:24
    at arrayEach (C:\Users\CalvinLappy\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (C:\Users\CalvinLappy\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3345:13)
    at displayErrors (C:/Users/CalvinLappy/.atom/packages/jshint/index.js:201:4)
    at lint (C:/Users/CalvinLappy/.atom/packages/jshint/index.js:275:2)
    at complete (C:\Users\CalvinLappy\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
    at delayed (C:\Users\CalvinLappy\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)
```
### Commands

```
     -0:27.4.0 tree-view:remove-project-folder (div.header.list-item)
     -0:24.2.0 project-find:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap",
      "jslint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.12
jshint, v1.8.3
linter, v1.10.0
linter-csslint, v1.1.0

# Dev
No dev packages
```

**Comment by ArtskydJ** [comment]
Is the shadow dom enabled?

Have you tried disabling `atom-jsint`, restarting atom, and enabling `atom-jshint`?

**Comment by wiky** [comment]
+1

**Comment by ashrussell** [comment]
witnessed this issue with atom 1.3.3, disabled all other packages to see if conflicts had occurred, restarted atom just with jshint enabled and same problem

**Comment by Softsapiens** [comment]
The same with atom 1.4.0.

**Comment by subtirelumihail** [comment]
Same with atom 1.4.3 :(

**Comment by ramonrails** [comment]
1. downloaded a free wordpress theme (https://wordpress.org/themes/libretto/)
2. opened the folder in atom
3. clicked on js/customizer.js

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.5


### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /Users/ram/.atom/packages/jshint/index.js:166

TypeError: Cannot read property 'querySelector' of null
    at addReasons (/Users/ram/.atom/packages/jshint/index.js:166:41)
    at displayError (/Users/ram/.atom/packages/jshint/index.js:192:2)
    at /Users/ram/.atom/packages/jshint/index.js:199:24
    at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
    at displayErrors (/Users/ram/.atom/packages/jshint/index.js:199:4)
    at lint (/Users/ram/.atom/packages/jshint/index.js:273:2)
    at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
    at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "highlight-column",
      "indent-guide-improved",
      "tree-view-git-status",
      "linter-ruby-reek",
      "rails-model-schema",
      "linter-ruby",
      "markdown-preview",
      "markdown-pdf",
      "markdown-preview-plus",
      "markdown-scroll-sync",
      "wrap-guide",
      "autocomplete-python",
      "autocomplete-ruby",
      "copy-as-rtf",
      "css-edit-groups",
      "css-to-inline",
      "ex-mode",
      "fonts",
      "git-control",
      "line-diff-details",
      "pdf-view",
      "react",
      "ruby-bundler"
    ],
    "projectHome": "/Users/ram/work/projects",
    "themes": [
      "native-ui",
      "gruvbox-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
aligner, v0.22.0
aligner-ruby, v1.4.0
atom-everydayrails-rspec, v0.4.0
atom-markdown-katex, v0.5.9
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-json, v1.9.1
coffee-compile, v0.21.1
color-picker, v2.1.1
cucumber, v0.5.0
cucumber-autocomplete, v0.6.3
emmet, v2.4.3
file-icons, v1.7.11
formatter-coffeescript, v0.1.1
git-diff-details, v1.3.0
go-to-view, v0.3.0
gruvbox-syntax, v2.3.1
javascript-snippets, v1.2.1
jsformat, v0.9.3
jshint, v1.8.5
language-javascript-semantic, v0.2.1
linter, v1.11.4
linter-coffeescript, v1.0.0
linter-jshint, v2.1.0
markdown-table-formatter, v2.8.3
merge-conflicts, v1.4.2
native-ui, v0.18.2
pigments, v0.26.3
project-manager, v2.9.7
rails-i18n, v0.1.3
rails-i18n-autocomplete, v0.3.0
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-syntax-replacer, v0.5.1
ruby-test-switcher, v1.2.1
tab-numbers, v0.3.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by paolostefan** [comment]
+1
Uninstalled this package after 2 minutes and ten red popup messages.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
