### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by LucasVilela** [sindresorhus/atom-jshint#169]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.6
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Users/lucasvilela/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/decompress-zip/node_modules/graceful-fs/polyfills.js:14

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/Users/lucasvilela/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/decompress-zip/node_modules/graceful-fs/polyfills.js:14:9)
    at lint (/Users/lucasvilela/.atom/packages/jshint/index.js:229:10)
    at complete (/Users/lucasvilela/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/lodash/index.js:7697:25)
    at delayed (/Users/lucasvilela/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/lodash/index.js:7707:11)
```
### Commands

```
     -5:32.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  8x -5:29.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:23.5.0 core:save (atom-text-editor.editor.is-focused)
     -5:14.1.0 open-in-browser:open-tree-view (span.name.icon.icon-file-text)
     -5:05.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:04.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:03.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -5:03.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:01.1.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:55.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:55.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -4:54.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:53.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:50.5.0 core:select-all (atom-text-editor.editor.is-focused)
  7x -0:24.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.1.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "activate-power-mode",
      "linter-jshint",
      "linter-ruby"
    ],
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.4 (inactive)
atom-beautify, v0.29.10 (active)
atom-ternjs, v0.14.2 (active)
auto-detect-indentation, v1.1.0 (active)
color-picker, v2.2.2 (active)
emmet, v2.4.3 (active)
erb-helper, v1.0.1 (inactive)
javascript-snippets, v1.2.1 (active)
jshint, v1.8.6 (active)
linter, v1.11.16 (active)
linter-csslint, vundefined (active)
linter-jshint, v2.1.0 (inactive)
linter-ruby, v1.2.2 (inactive)
minimap, v4.24.7 (active)
open-in-browser, v0.4.7 (active)
open-recent, v5.0.0 (active)
script, v3.9.0 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (active)
terminal-plus, v0.14.5 (active)
todo-show, v1.7.0 (inactive)
wakatime, v6.0.10 (active)
webbox-color, v0.5.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by codeforkorea** [comment]
same here

**Comment by dkmin** [comment]
same here

**Comment by FrancoAguilera** [comment]
and here

**Comment by visby** [comment]
It seems to happen for me when an opened Javascript file gets renamed, and in consequence doesn't physically exist any longer on disk.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
