### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by airwolff** [sindresorhus/atom-jshint#171]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.6
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/decompress-zip/node_modules/graceful-fs/polyfills.js:14

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/decompress-zip/node_modules/graceful-fs/polyfills.js:14:9)
    at lint (/Users/AndyWolff/.atom/packages/jshint/index.js:229:10)
    at complete (/Users/AndyWolff/.atom/packages/jshint/node_modules/lodash/index.js:7697:25)
    at delayed (/Users/AndyWolff/.atom/packages/jshint/node_modules/lodash/index.js:7707:11)
```
### Commands

```
     -7:46.6.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -7:36.8.0 tree-view:add-folder (span.name.icon.icon-file-directory)
  3x -7:35 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:31.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:27.5.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -7:25 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:04.2.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -6:50.6.0 window:save-all (atom-text-editor.editor.is-focused)
     -0:47.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.2.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "keybinding-resolver",
      "bottom-dock",
      "linter-sass-lint",
      "intentions",
      "linter-php",
      "linter-phpcs",
      "linter-ruby",
      "linter-spell",
      "linter-spell-html",
      "linter"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-jshint, v2.0.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-ui, v1.3.6 (active)
auto-detect-indentation, v1.2.0 (active)
autoclose-html, v0.23.0 (active)
bottom-dock, v0.4.4 (inactive)
color-picker, v2.2.2 (active)
highlight-selected, v0.11.2 (active)
intentions, v1.1.2 (inactive)
jshint, v1.8.6 (active)
linter, v1.11.18 (inactive)
linter-bootlint, v1.0.2 (active)
linter-csslint, v1.3.3 (active)
linter-eslint, v7.3.2 (active)
linter-htmlhint, v1.3.0 (active)
linter-jscs, v4.1.0 (active)
linter-jshint, v3.0.0 (active)
linter-jsonlint, v1.3.0 (active)
linter-manager, v0.2.12 (active)
linter-php, v1.2.0 (inactive)
linter-phpcs, v1.4.1 (inactive)
linter-ruby, v1.2.2 (inactive)
linter-sass-lint, v1.7.1 (inactive)
linter-spell, v0.12.0 (inactive)
linter-spell-html, v0.6.0 (inactive)
linter-tidy, v2.2.0 (active)
merge-conflicts, v1.4.4 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
