### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by sparanoid** [sindresorhus/atom-jshint#172]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.6
### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Users/distiller/atom/out/app/src/decoration-manager.coffee:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1657:37)
    at displayError (/Users/sparanoid/.atom/packages/jshint/index.js:189:9)
    at /Users/sparanoid/.atom/packages/jshint/index.js:199:24
    at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/lodash/index.js:3345:13)
    at displayErrors (/Users/sparanoid/.atom/packages/jshint/index.js:199:4)
    at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/lodash/index.js:7697:25)
    at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/lodash/index.js:7707:11)
```
### Commands

```
     -0:55.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:42.9.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -0:36 core:paste (atom-text-editor.editor.is-focused)
     -0:35.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:33.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:30.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.8.0 core:delete (atom-text-editor.editor.is-focused)
     -0:27 core:move-up (atom-text-editor.editor.is-focused)
     -0:26.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:25.9.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:25.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:23 pane:show-item-4 (atom-text-editor.editor.is-focused)
  2x -0:21.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:15.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:15.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.3.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "term2",
      "character-table",
      "docblockr",
      "html-entities",
      "travis-ci-status",
      "atom-ternjs",
      "pangu"
    ],
    "projectHome": "~/Git",
    "telemetryConsent": "no"
  },
  "jshint": {
    "supportLintingJsx": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (active)
atom-terminal, v0.8.0 (inactive)
atom-wrap-in-tag, v0.6.0 (inactive)
character-table, v0.4.3 (inactive)
color-picker, v2.2.2 (active)
docblockr, v0.8.7 (inactive)
highlight-selected, v0.11.2 (active)
html-entities, v0.4.0 (inactive)
jshint, v1.8.6 (active)
language-html-swig, v2.0.1 (active)
language-liquid, v0.5.1 (active)
language-lua, v0.9.11 (active)
language-nginx, v0.6.2 (active)
pangu, v0.5.0 (inactive)
pigments, v0.37.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
sync-settings, v0.7.2 (active)
term2, v0.9.21 (inactive)
travis-ci-status, v1.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
