### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by moretti** [sindresorhus/atom-jshint#57]
I'm getting ton of exceptions similar to this one with Atom 0.170.0 and jshint@1.1.4:

```
/Users/paul/.atom/packages/jshint/index.js:98
TypeError: Cannot read property '0' of undefined
  at updateStatusbar (/Users/paul/.atom/packages/jshint/index.js:98:15)
  at displayErrors (/Users/paul/.atom/packages/jshint/index.js:203:2)
  at lint (/Users/paul/.atom/packages/jshint/index.js:197:2)
  at delayed (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5408:27)
```
Looks like the error is triggered every time I'm editing an invalid jsx file.

![screen](https://cloud.githubusercontent.com/assets/1186409/5720635/29b28244-9b27-11e4-87e9-dc6f5bc843b8.jpg)

**Comment by sindresorhus** [comment]
Can you share the content of the file you got those errors with?

**Comment by moretti** [comment]
I can reproduce the error by creating a new file (i.e. `test.js`) and pasting the following svg:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<circle transform="translate(8 0)" cx="0" cy="16" r="0">
<animate attributeName="r" values="0; 4; 0; 0" dur="1.2s" repeatCount="indefinite" begin="0"
keytimes="0;0.2;0.7;1" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.6 0.4 0.8" calcMode="spline" />
</circle>
<circle transform="translate(16 0)" cx="0" cy="16" r="0">
<animate attributeName="r" values="0; 4; 0; 0" dur="1.2s" repeatCount="indefinite" begin="0.3"
keytimes="0;0.2;0.7;1" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.6 0.4 0.8" calcMode="spline" />
</circle>
<circle transform="translate(24 0)" cx="0" cy="16" r="0">
<animate attributeName="r" values="0; 4; 0; 0" dur="1.2s" repeatCount="indefinite" begin="0.6"
keytimes="0;0.2;0.7;1" keySplines="0.2 0.2 0.4 0.8;0.2 0.6 0.4 0.8;0.2 0.6 0.4 0.8" calcMode="spline" />
</circle>
</svg>
```

**Comment by sindresorhus** [comment]
Depends on https://github.com/shmatov/jshint-jsx/issues/5

// @shmatov

**Comment by sindresorhus** [comment]
Was fixed in `jshint-jsx`. Just reinstall this plugin.

**Comment by moretti** [comment]
Thanks :+1:
