### ISSUE TITLE
Failed to activate the jshint package

### ISSUE THREAD

**Issue by fincha** [sindresorhus/atom-jshint#83]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.6

### Stack Trace

Failed to activate the jshint package

```
At undefined is not a function

TypeError: undefined is not a function
  at /Users/fribu/.atom/packages/jshint/index.js:263:10
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
  at registerEvents (/Users/fribu/.atom/packages/jshint/index.js:258:17)
  at Object.plugin.activate (/Users/fribu/.atom/packages/jshint/index.js:298:2)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:292:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:34.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:22 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
coffeescript-check, v0.0.3
coffeescript-preview, v1.0.0
color-picker, v1.7.0
html-entities, v0.4.0
html-tab, v1.0.1
jshint, v1.3.6
language-lua, v0.9.2
linter, v0.12.2
linter-lua, v0.1.5
linter-luacheck, v0.4.0
text-to-string-for-javascript-converter, v0.0.7

# Dev
No dev packages
```

**Comment by paulbhartzog** [comment]
solution?

**Comment by kevva** [comment]
I think this was fixed in https://github.com/sindresorhus/atom-jshint/commit/91e9adf2306edf940b8c08f5bad3c2948d266394. Can you check what's on line `263`?
