### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by philidem** [sindresorhus/atom-jshint#85]
Error seems to happen when I run jshint on file that has error.

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.7
### Stack Trace

Uncaught TypeError: Cannot read property 'querySelectorAll' of null

```
At /Users/philidem/.atom/packages/jshint/index.js:153

TypeError: Cannot read property 'querySelectorAll' of null
  at addReasons (/Users/philidem/.atom/packages/jshint/index.js:153:39)
  at displayError (/Users/philidem/.atom/packages/jshint/index.js:139:2)
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1314:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3355:13)
  at displayErrors (/Users/philidem/.atom/packages/jshint/index.js:237:4)
  at lint (/Users/philidem/.atom/packages/jshint/index.js:228:2)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7681:27)

```
### Commands

```
     -0:23.2.0 core:move-up (input.hidden-input)
     -0:22.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:22.3.0 editor:newline (input.hidden-input)
     -0:21 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:20.7.0 core:backspace (input.hidden-input)
     -0:20 core:move-up (input.hidden-input)
     -0:18.8.0 editor:newline (input.hidden-input)
  5x -0:13.9.0 core:backspace (input.hidden-input)
     -0:10.4.0 editor:newline (input.hidden-input)
     -0:09.1.0 core:move-up (input.hidden-input)
     -0:08.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:08.2.0 core:move-down (input.hidden-input)
  4x -0:05.4.0 core:backspace (input.hidden-input)
     -0:02.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:01.3.0 editor:newline (input.hidden-input)
     -0:01.0 core:save (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "node_modules",
      ".cache"
    ],
    "disabledPackages": [
      "autocomplete",
      "language-jsx",
      "autocomplete-paths"
    ]
  },
  "jshint": {
    "validateOnlyOnSave": true,
    "supportLintingJsx": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.27.9
color-picker, v2.0.2
file-icons, v1.5.5
jsformat, v0.8.1
jshint, v1.3.7
language-csharp, v0.5.0
language-marko, v0.4.15
language-typescript, v0.15.0
open-recent, v2.2.2
pain-split, v1.4.0
project-manager, v1.15.7
react, v0.11.8
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by philidem** [comment]
Problem only happens when `Use Shadow DOM` is _unchecked_ in general Atom Settings.

**Comment by sindresorhus** [comment]
As it says under the `Use Shadow DOM` option it's going away eventually, and you should check it. This plugin is not supported with it unchecked.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
