### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by celsom3** [sindresorhus/atom-jshint#86]
[Enter steps to reproduce below:]
1. Updated Atom
2. Opened Project

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.7
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/celso/.atom/packages/jshint/index.js:105

TypeError: undefined is not a function
  at updateStatusbar (/Users/celso/.atom/packages/jshint/index.js:105:13)
  at displayErrors (/Users/celso/.atom/packages/jshint/index.js:236:2)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7681:27)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "remember-session",
      "auto-indent",
      "auto-indent",
      "atom-color-highlight"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.6.4
color-picker, v2.0.6
emmet, v2.3.10
jshint, v1.3.7
linter-php, v0.0.15
meteor-api, v2.19.0
meteor-helper, v0.25.0
minimap, v4.10.0
pigments, v0.8.0
project-manager, v1.15.10
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by Sebi55** [comment]
I do have the same problem. Did you find a solution?

**Comment by thefirstave** [comment]
Me too. I can't work now anymore since this error occurred. At least not with Atom.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
