### ISSUE TITLE
Failed to load the jshint package

### ISSUE THREAD

**Issue by CrackerakiUA** [sindresorhus/atom-jshint#92]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.8

### Stack Trace

Failed to load the jshint package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\Crack\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\Crack\.atom\packages\jshint\node_modules\emissary\lib\behavior.js:7:13)
    at Object.<anonymous> (C:\Users\Crack\.atom\packages\jshint\node_modules\emissary\lib\behavior.js:120:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\Crack\AppData\Local\atom\app-1.0.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "flatland-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "wrap",
      "wrap",
      "wrap",
      "wrap",
      "wrap",
      "wrap",
      "wrap",
      "wrap",
      "node-debugger",
      "term2",
      "term2",
      "term2",
      "term2"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-terminal-panel, v4.4.4
auto-detect-indentation, v0.4.2
browser-plus, v0.0.23
change-case, v0.6.0
change-tabs, v0.2.0
color-picker, v2.0.7
emmet, v2.3.11
flatland-dark-ui, v0.2.4
git-log, v0.4.1
jshint, v1.3.8
monokai, v0.14.0
pdf-view, v0.22.0
project-manager, v1.15.10
remote-sync, v3.1.2
Sublime-Style-Column-Selection, v1.3.0
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by arthurvr** [comment]
Seems like an installation error. Does reinstalling help?

**Comment by sindresorhus** [comment]
Yup, looks like an install corruption.

**Comment by CrackerakiUA** [comment]
Yeah, after reinstall i don't see that error anymore.
